# docker-compose.yml
services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend


  redis-exporter:
    image: oliver006/redis_exporter
    ports:
      - "9121:9121"
    depends_on:
      - redis
    networks:
      - backend
    command:
      - "--redis.addr=redis://redis:6379"



  web:
    build: .
    container_name: django-web
    command: >
     sh -c "python manage.py collectstatic --noinput &&
            python manage.py initbots &&
            daphne -b 0.0.0.0 -p 8000 blg.asgi:application"

    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    environment:
      - MINI_SERVER_URL=http://10.0.0.240:11434
      - DJANGO_SETTINGS_MODULE=blg.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - OLLAMA_URL=http://ollama:11434
      - USE_CELERY=True
    depends_on:
      - redis
      - ollama
    networks:
      - backend
    extra_hosts:
      - "mini_server:10.0.0.240"


  celery:
    build: .
    container_name: django-celery
    command: celery -A blg worker -l info -c 4
    volumes:
      - .:/app
    environment:
      - MINI_SERVER_URL=http://10.0.0.240:11434
      - DJANGO_SETTINGS_MODULE=blg.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - OLLAMA_URL=http://ollama:11434
      - USE_CELERY=True
    depends_on:
      - redis
      - web
      - ollama
    networks:
      - backend

  celery-exporter:
    image: danihodovic/celery-exporter
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "9808:9808"
    depends_on:
      - redis
      - celery
    networks:
      - backend

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./init.sh:/init.sh
    restart: unless-stopped
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL:-gemma3:1b}
    entrypoint: ["/bin/sh", "/init.sh"]
    healthcheck:
      test: ["CMD", "curl", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
        - backend

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_BASIC_AUTH=${FLOWER_USER}:${FLOWER_PASSWORD}
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - web
      - celery
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - backend


volumes:
  prometheus_data:
  grafana_data:
  ollama-data:

networks:
  backend:
   
    name: backend